apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: vlbagents.extensions.example.com
    annotations:
        "helm.sh/hook": crd-install
spec:
    scope: Namespaced
    group: extensions.example.com
    version: v1
    names:
        plural: vlbagents
        kind: Vlbagent
        singular: vlbagent
